### ISSUE TITLE
Availability check failed

### ISSUE THREAD

**Issue by charlesbradber** [ICUK-Net/icuk-broadband-checker-php#1]
Hello,
We seem to be getting "Availability check failed" when the API details are correctly added to"examples/api.php" in a normal text format.

Do you think it should be encoded in base64 like the official API says?

We entered the username and password from the API control we created here - https://control.interdns.co.uk/api.aspx is this correct?

I look forward to your help :)

**Comment by boronbritt** [comment]
You should take a look at your account on /api.aspx and see if the IP permissions are set up correctly to allow the server to access the api and the permissions on /api.aspx are setup to allow the broadband module. 

If this does not work then it will be helpful if you could provide exact setup with the api.php and wherever you rendered the BroadbandAvailability class including the information of where you located these files relative to the webroot aswell as the php error log

You would be correct in assuming that you just enter the username and password from that page, base64 encoding and such is done internally inside of the library

**Comment by charlesbradber** [comment]
Thank you for your reply, I have added my server IP "65.181.111.156" into ICUK, with all permissions enabled.
![image](https://github.com/BoronBGP/icuk-broadband-checker-php/assets/29871999/719bb5a2-967e-4498-ba85-1698857684e4)
I have the code located at "https://sussexfibre.com/checker/examples/".
API file is the same password and username we use to log in to "https://api.interdns.co.uk/" so I know that part of it works. 

Have you got an email so I can send some more 'secure' details over if required?

**Comment by boronbritt** [comment]
Sure, you can email us over at support@icuk.net

**Comment by boronbritt** [comment]
You also need to change the line in index.php to specify /checker/examples/api.php rather then /api.php as that is the directory in which the checker api file is contained, this doesnt seem to fix the problem fully though

**Comment by BoronBGP** [comment]
Seems to be working on the website this is posted about now so will close issue unless anything else comes up
